### ISSUE TITLE
exaple wan't start

### ISSUE THREAD

**Issue by boris-741** [flamendless/Slab#142] opened 2022-10-08 15:40 UTC
on launching the main.lua (copy of github) - I get an error: (v 1.0.0) love 11.4

Error

/Internal/UI/ComboBox.lua:86: selected must be of type string

Traceback

[love "callbacks.lua"]:228: in function 'handler'
[C]: in function 'assert'
/Internal/UI/ComboBox.lua:86: in function 'BeginComboBox'
SlabTest.lua:2520: in function 'Begin'
main.lua:37: in function 'update'
[love "callbacks.lua"]:162: in function <[love "callbacks.lua"]:144>
[C]: in function 'xpcall'

**Comment by flamendless** [comment] 2022-10-09 01:16
Hi, thanks for reporting. What branch did you download?

**Comment by boris-741** [comment] 2022-10-10 07:07
current - 4807bbf
love - 11.4

**Comment by flamendless** [comment] 2022-10-10 13:32
Hi, what are the steps to reproduce this error? Launching the sample works fine for me

**Comment by boris-741** [comment] 2022-10-10 15:00
1. clone the repository
2. go to root folder
3. launch mine.lua
OS Windows 10

version 0.9 starts as expected

**Comment by flamendless** [comment] 2022-10-15 04:27
Hi, can you show a video replicating this issue? Thank you

**Comment by flamendless** [comment] 2022-10-17 04:07
Hi @boris-741  I have found out the issue, turns out you were using the `v1.0.0` branch which is still in development phase, I thought you were using the `main` branch. It's already fixed in the latest commit :) Thank you

**Closed by flamendless** 2022-10-17 04:07 UTC
